### ISSUE TITLE
Create Demo Website

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#10]
Create a demo website with our auth service and the eID infrastructure.

**Comment by m273d15** [comment]
Similar to #31 . We have to clarify whether the result of #31 is sufficient.

**Comment by nils-wisiol** [comment]
I'd love to have a shiny working example, but for now let's focus on functionality. Hopefully there will be time to add this later.

**Comment by larissazech** [comment]
Done. A shiny example as extension of this issue will be done with #77. Closed.
