### ISSUE TITLE
Prepare presentation

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#12]

**Comment by baris1892** [comment]
Google Drive: https://docs.google.com/presentation/d/1mIG4MSQhuhfzyQn_7Gm-NV-9PpWc6D6GUfDv0WGPL_0/edit?usp=sharing

- - - 
[Präsentation 01.pdf](https://github.com/swp-fu-eid/eid-fu-swp/files/1204440/Prasentation.01.pdf)
