### ISSUE TITLE
Create infrastructure overview

### ISSUE THREAD

**Issue by auvin** [swp-fu-eid/eid-fu-swp#14]
Create a figure which describes all needed components and the communication between them in the eid authentication process (like the figure on this page: https://www.bsi.bund.de/EN/Topics/ElectrIDDocuments/German-eID/eID-Infrastructure/eID-Infrastructure_node.html). Add the swp-component to the figure and adjust the communication. 
As we currently can't describe the whole process, the figure should be work in progress and adjusted if necessary.

**Comment by auvin** [comment]
First try with oAuth ([example](https://de.wikipedia.org/wiki/OAuth#/media/File:Authorization-Code-Grant-Flow.png)) and the results of the discussions last week. Maybe a flow chart would be the better option. Here is the link, if you want to edit it: [eID-Infrastructure](https://docs.google.com/drawings/d/15qdG7k7ANY33JpxsFgph7BHGC4hVjPTMv027GnPRqBw/edit?usp=sharing)

![eid](https://user-images.githubusercontent.com/9862548/29026502-5ef0b5ba-7b7c-11e7-893e-13a605e46109.png)

1. Request resource
2. GET resource
3. HTTP 302 authorization request
4. GET authorization request
5. Redirection to eID-client if the client is running
6. Focus eID-client
7. Input authorization (apply eID-card)
8. Some communication with eID-server? I don't know.
9. Redirection
10. POST Confirmation and authorization
11. HTTP 302 Authorization code
12. Authorization code
13. POST authorization code and redirection URL
14. Access token and optional refresh token
15. GET resource with access token
16. HTTP 200 resource
17. HTTP 200 resource
18. Display resource

**Comment by larissazech** [comment]
![flowchart](https://user-images.githubusercontent.com/30339953/29159700-d64746c6-7daf-11e7-8014-e535c909a813.jpg)

These are the results of yesterday's discussion. We decided to switch from an organization chart to a flow chart. We will discuss this version today and publish the final version to the wiki afterwards.

For editing, please download this .txt-file and change its extension to .xml manually (can't upload xml here). 
[FlowChart.txt](https://github.com/swp-fu-eid/eid-fu-swp/files/1213995/FlowChart.txt)
Then, go to [draw.io](https://www.draw.io/) and upload the xml-file.

**Comment by larissazech** [comment]
Update:
![flowchart_update](https://user-images.githubusercontent.com/30339953/29163005-6771fdde-7dbb-11e7-8ede-feee45894dd7.jpg)

Tried to make it more obvious which message belongs to which standard. 

[FlowChart_update.txt](https://github.com/swp-fu-eid/eid-fu-swp/files/1214277/FlowChart_update.txt)

**Comment by larissazech** [comment]
# OpenID Connect
Considering only the OpenID Connect Process, this is how the communication protocol is specified in the official spec ([OpenID Connect Core 1.0](http://openid.net/specs/openid-connect-core-1_0.html)):
![openid_connect_original](https://user-images.githubusercontent.com/30339953/29163833-f8f69c36-7dbd-11e7-9ad2-a32c96f63c44.JPG)
1.The RP (Client) sends a request to the OpenID Provider (OP). 
2.The OP authenticates the End-User and obtains authorization. 
3.The OP responds with an ID Token and usually an Access Token. 
4.The RP can send a request with the Access Token to the UserInfo Endpoint. 
5.The UserInfo Endpoint returns Claims about the End-User. 

Based on the above flow chart, this is what I assume our OpenID Connect Process looks like:
![openid_connect_oursolution](https://user-images.githubusercontent.com/30339953/29163912-296de52c-7dbe-11e7-8763-677da8d26a9b.JPG)

We should discuss if this discrepancy is tolerable.

[OpenID_Connect.txt](https://github.com/swp-fu-eid/eid-fu-swp/files/1214348/OpenID_Connect.txt)

**Comment by janles** [comment]
I reviewed the sequence diagram in respect of the following two papers from yesterday: [TR-eID-Server](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03130/TR-03130_TR-eID-Server_Part1.pdf) and [Heise: OpenID Connect: Login mit OAuth, Teil 1 – Grundlagen](https://www.heise.de/developer/artikel/OpenID-Connect-Login-mit-OAuth-Teil-1-Grundlagen-2218446.html?seite=2)  

- I think that in our case the RP is the KVV and not the Browser.
- Heise wrote the following: 

> Nach Abschluss der Authentifizierung stellt der Autorisierungsserver der Anwendung (wie bei OAuth üblich) einen Autorisierungs-Code aus. **Dieser wird über den User Agent via HTTP Redirect an den Mediendienst gesendet.**

I guess the browser (if the browser is really needed) will transport the information from OP to RP (KVV), only. So, (4) Access Token of your picture should point from "Browser" to "KVV", too.

We should present the second sequence diagram, today.

**Comment by larissazech** [comment]
Updated the flow chart by adding the eID "Ausweis" as new entity. Layout suffered a little.
![FlowChart](https://user-images.githubusercontent.com/30339953/29202275-ec253c84-7e66-11e7-9fe0-f23b543ebb21.jpg)
[FlowChart.pdf](https://github.com/swp-fu-eid/eid-fu-swp/files/1216992/FlowChart_update_Ausweis.pdf)
[FlowChart.txt](https://github.com/swp-fu-eid/eid-fu-swp/files/1216995/FlowChart_update_Ausweis.txt)

And the updated OpenID Connect scheme as discussed yesterday:
![openid_connect_original](https://user-images.githubusercontent.com/30339953/29202319-493509f4-7e67-11e7-9e4a-1e517b5fea4b.JPG)
![openid_connect_oursolution](https://user-images.githubusercontent.com/30339953/29202320-493a6962-7e67-11e7-84f5-df8f47ef67db.JPG)
[OpenID_Connect.txt](https://github.com/swp-fu-eid/eid-fu-swp/files/1217018/OpenID_Connect.txt)


I consider this the final versions so far and am going to add it to the wiki.

**Comment by larissazech** [comment]
Added it the wiki (see [Software Architecture](https://github.com/swp-fu-eid/eid-fu-swp/wiki/Software-Architecture)). Closed.
