### ISSUE TITLE
Run PersoSim

### ISSUE THREAD

**Issue by auvin** [swp-fu-eid/eid-fu-swp#15]
I was able to run the PersoSim-cardreader together with open ecard (eID-client for linux). PersoSim provides sample eID-cards which are stored as xml-files. Open ecard identicates these cards as _german electronic identity cards_.
The redirection from the [petition-site](https://epetitionen.bundestag.de/epet/peteinreichen/einzeln.html), which allowed login with eID, to open ecard also worked. The client displayed the information about the service provider (e.g Deutscher Bundestag) and the requested information, but i was not able to enter the pin correctly, although i read the pin out of the xml file.

### PersoSim
1. ```sudo apt-get update && sudo apt-get install pcscd pcsc-tools libpcsclite-dev```
2. Download [PersoSim-driver](https://persosim.secunet.com/de/download/) for linux and extract.
3. Change to the drivers directory and execute ```make && sudo make install```
4. ```sudo service pcscd restart```
5. Download the [simulator](https://persosim.secunet.com/de/download/) for linux and extract.
6. Change to the simulators directory and execute ```./PersoSim```
7. Now the cardreader is running and one can select the eIDs with __Select Personalization__ -> __Select predefined Perso template__.
8. In another terminal one could run ```pcsc_scan``` which provides additional debug information.

### Open eCard
1. Download openecard.jnlp from [openecard.org](https://www.openecard.org/download/pc/).
2. ```sudo apt-get install icedtea-8-plugin```
3. Open _openecard.jnlp_ with _IcedTea Java Web Start_.
4. In my case then there was an new icon in my taskbar, with a left click i could open the open ecard application.
5. If a sample card was inserted in the cardreader you should see it in the open ecard app with the information _PersoSimHandshake 00 00_.

**Comment by BenjaminKeller** [comment]
I tested it on Windows 10 (failed to install drivers) and Windows 7 (installation works but no card reader is detected by AusweisApp). I think we should use Ubuntu and your installation guide for now.

**Comment by BenjaminKeller** [comment]
I had to install the _IcedTea Java Web Start_ via `sudo apt-get install icedtea-netx`. I got it working on windows 10 finally by running Ubuntu in Hyper-V.

**Comment by larissazech** [comment]
Closed.
