### ISSUE TITLE
Extract test certificates of example project

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#21]
Additionally provide documentation how we can use the certificate!

**Comment by Armagetron** [comment]
The file https://www.ausweisapp.bund.de/fileadmin/user_upload/Software/Governikus-Demo.zip contains the certificates. The path to the keys in the archive is ```Governikus-Demo\DemoApp\misc\src\testKeys```

**Comment by BenjaminKeller** [comment]
Sorry, but this seems to be wrong. The `Governikus-Demo/ReadMe.txt` says:

> Quote

Sie können den mitgelieferten Tomcat sofort nutzen. Wenn Sie 
das wünschen, können Sie auch einen eigenen Tomcat entsprechend
modifizieren. Führen Sie hierfür die folgenden Schritte durch:

Konfigurieren Sie den https support im Tomcat 
 1. kopieren Sie **tls-ssl-commcert.p12** in das folgende Verzeichnis
    $CATALINA_HOME/conf/tls-ssl-commcert.p12
 2. Fügen Sie den folgenden Block zu 
	$CATALINA_HOME/conf/server.xml zu.
    <Connector protocol="org.apache.coyote.http11.Http11Protocol"
       port="8443" SSLEnabled="true"
       maxThreads="150" scheme="https" secure="true"
       clientAuth="false" sslProtocol="TLS"
       keystoreFile="conf/tls-ssl-commcert.p12"
       keystoreType="PKCS12"
       keystorePass="123456" />
 3. kopieren Sie die Datei dist/AutentSAMLDemo.war in
    $CATALINA_HOME/webapps/
 4. starten Sie Ihren Tomcat mit dem entsprechenden Kommando 
	$CATALINA_HOME/bin/startup.sh unter Unix/Linux
    oder mit $CATALINA_HOME/bin/startup.bat unter Windows.
 6. Öffnen Sie https://localhost:8443/AutentSAMLDemo/ in Ihrem 
	Browser.

**Hinweis:
Sie können nur Adressen verwenden, die unter 
der URL https://localhost:8443 erreichbar sind. 
Im konfiguerierten Berechtigungszertifikat ist diese Adresse als 
SubjectURL hinterlegt. Bei jeder anderen Adresse für die 
AutentSAMLDemo wird die AusweisApp2 mit einer Sicherheitswarnung 
abbrechen.**

> Quote end

Therefore, we have to use `Governikus-Demo\apache-tomcat-8.5.5\conf\tls-ssl-commcert.p12`.
