### ISSUE TITLE
Provide a logout mechanism

### ISSUE THREAD

**Issue by janles** [swp-fu-eid/eid-fu-swp#26]
@larissazech mentioned in Slack that we should provide a logout mechanism

**Comment by janles** [comment]
In my opinion a logout mechanism for our SSO (Single-Sign-On) isn't required. You don't have to logout from the OpenID Provider.  
The webservice (our dummy webpage) should provide this mechanism. With SSO you can login to e.g. an account of the KVV and the KVV has to make it possible to logout.

**Comment by larissazech** [comment]
Implemented. Can be done with "<BOILERPLATE_DOMAIN>/api/eidopenid/logout". Closed.
