### ISSUE TITLE
Travis Reports Successful Even If Tests Fail

### ISSUE THREAD

**Issue by nils-wisiol** [swp-fu-eid/eid-fu-swp#28]
Check container exit code like [this](https://github.com/desec-io/desec-stack/blob/master/test-api#L45)

**Comment by Armagetron** [comment]
Should now work with 5f1362337ec0ef7c558cfa4f5819a50f6597b2c7

**Comment by Armagetron** [comment]
The problem was, that we need to check for the container not the compose. Correct line is ```exit $(docker ps -a -f exited=1 -q | wc -l | tr -d ' ')```
