### ISSUE TITLE
Code Style Policy

### ISSUE THREAD

**Issue by nils-wisiol** [swp-fu-eid/eid-fu-swp#30]
Please use a common policy for coding style, including a policy on tabs vs spaces. Please use `\n` (unix) line breaks everywhere.

#25 both adds a [tab-indented file](https://github.com/swp-fu-eid/eid-fu-swp/pull/25/files#diff-bc4d3b2f297a4f9f288530fb5d5d1098) and [changes existing files from tab indention to space indention](https://github.com/swp-fu-eid/eid-fu-swp/pull/25/files#diff-220a16a428af1359c0b5099867a7a4ef). Please avoid whitespace-only changes and stick to one of tabs or spaces, preferably the one that is already used in the project.

**Comment by m273d15** [comment]
I found a guideline from google: https://google.github.io/styleguide/pyguide.html
There are multiple pyline configurations that configure this styleguide.
@Armagetron mentioned that it would be useful to use a Django guideline, but i found only a prosaic specification without a full technical solution: https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/

**Comment by nils-wisiol** [comment]
If you wanna go with that, no problem. For us it is sufficient to decide tabs/spaces and stick to unix newlines without a full-blown linter.

Also, PEP has some nice style advice.

**Comment by m273d15** [comment]
Alright so we are using 4 spaces as tab and \n from unix! We will see whether a linter will be needed.
Example vim config:
```
let spaces=4
execute "set tabstop=".spaces
execute "set softtabstop=".spaces
execute "set shiftwidth=".spaces
set expandtab
set smarttab
```

**Comment by nils-wisiol** [comment]
:+1:
