### ISSUE TITLE
eID Server implementation

### ISSUE THREAD

**Issue by Armagetron** [swp-fu-eid/eid-fu-swp#32]
I started the implementation of the eID Server component specified in [BSI TR-03130 Technical Guideline eID-Server, Part I: Functional Specification, Version 2.0.2](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03130/TR-03130_TR-eID-Server_Part1.pdf). This file is accompanied by a zip file [BSI TR-03130 TR-eID -Server Schemadateien](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03130/TR-03130_TR-eID-Server_WSDL.zip).

I tried to generate a web service from the WSDL with [soapfish](https://github.com/FlightDataServices/soapfish). This failed.

So I ran the WSDL trough an online [WSDL analyzer](https://www.wsdl-analyzer.com/). This revealed that ```external/saml-schema-assertion-2.0.xsd``` links to the, as of writing this, no longer available [xmldsig-core-schema.xsd](http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd). A [copy](https://web.archive.org/web/20170711185630/http://www.w3.org/TR/xmldsig-core/xmldsig-core-schema.xsd) is available in the wayback machine.

Next steps are to patch the ```external/saml-schema-assertion-2.0.xsd``` that links to the xsd and retry the entire soapfish process again.

**Comment by Armagetron** [comment]
soapfish requires lxml and iso8601 as dependencies.

**Comment by Armagetron** [comment]
The WSDL **is broken**!

Instead of
```
<wsdl:types>
	<xsd:schema>
		<xsd:import schemaLocation="TR-03130eID-Server.xsd"
			namespace="http://bsi.bund.de/eID/" />
	</xsd:schema>
</wsdl:types>
```
it has to be
```
<wsdl:types>
	<xsd:schema>
		<xsd:include schemaLocation="TR-03130eID-Server.xsd" />
	</xsd:schema>
</wsdl:types>
```
because the XSD implements the same namespace (see [w3schools](https://www.w3schools.com/xml/el_include.asp)).

**Comment by Armagetron** [comment]
@nils-wisiol @zervnet is there a way to report this?

**Comment by Armagetron** [comment]
Now using python-zsi and twisted for generation.

Patching of ```/usr/lib/python2.7/dist-packages/ZSI/twisted/WSresource.py``` is required to work on Ubuntu 17.04.

First, change ```from twisted.web.error import NoResource``` to ```from twisted.web.resource import NoResource```. Second, move ```DefaultHandlerChain``` over the ```WSAddressHandlerChainFactory``` definition.

**Comment by nils-wisiol** [comment]
Not sure on how to report this to BSI. Can you elaborate on what exactly is wrong, why it is wrong and where did you get this file from? I'll get in touch with BSI.

**Comment by Armagetron** [comment]
I split the task in some more issues.

#44, #45 and #46

**Comment by nils-wisiol** [comment]
Communication with the eID client for online authentication is described in [TR-03124-1](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03124/TR-03124-1.pdf?__blob=publicationFile), Section 2.5 (please see the chart on p14!). It uses the Extended Access Control Protocol (EAC Protocol) defined in [TR-03112-7](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil7.pdf?__blob=publicationFile) (Section 3.6). The eID Service Certificate ("Berechtigungszertifikat") is sent in Section 3.6.4.1 (see bottom of p. 50).

**Comment by larissazech** [comment]
We can only use Governikus' eID Server. Closed.
