### ISSUE TITLE
Decide for a project name

### ISSUE THREAD

**Issue by BenjaminKeller** [swp-fu-eid/eid-fu-swp#35]
As requested in #24 and #25 we have to find a name for this project. First suggestion:
```
eID-based single sign-on service
```
I would prefer to make a decision very soon as merging #24 and #25 depends on that!

**Comment by m273d15** [comment]
I like it. This is not carved in stone.
@Armagetron @larissazech @nielsgroth also approved this name.
Therefore 5/7 > 1/2 of the project approved the name!

**Comment by BenjaminKeller** [comment]
Thank you very much for your fast decision. We decided to use:
```
eID-based single sign-on service
```

**Comment by nils-wisiol** [comment]
:+1: 

ebsss? 
eibsoss?
ebassos?
ebassi?
