### ISSUE TITLE
Add .gitattributes

### ISSUE THREAD

**Issue by Armagetron** [swp-fu-eid/eid-fu-swp#38]
We want to add a ```.gitattributes``` file that handles line endings for us.

It could look like this (base on [this documentation](https://help.github.com/articles/dealing-with-line-endings/):
```
# Force LF on text files (requires git>=2.10)
* text=auto eol=lf

```
Has everyone a git version 2.10?

**Comment by larissazech** [comment]
On behalf of @m273d15, @nielsgroth and me: yes!

**Comment by Armagetron** [comment]
#39 PR created.
