### ISSUE TITLE
Integrate test certificates into nginx

### ISSUE THREAD

**Issue by BenjaminKeller** [swp-fu-eid/eid-fu-swp#42]
After we found the test certificates #21 and they are available to the web, we can give them to nginx and talk to the eID-Client.

**Comment by BenjaminKeller** [comment]
I added a [wiki page](https://github.com/swp-fu-eid/eid-fu-swp/wiki/Working-with-Test-Certificates-by-Governikus).

@nils-wisiol We cannot test this at the moment. Can you still give some feedback?

**Comment by nils-wisiol** [comment]
I believe these certificates are as good as any not-trusted, expired certificates for localhost. IMHO, these are not the eID Service Certificates ("Berechtigungszertifikat"). ([see also](https://github.com/swp-fu-eid/eid-fu-swp/issues/32#issuecomment-323505074))

**Comment by larissazech** [comment]
@Armagetron
