### ISSUE TITLE
Check that the received eID-token is valid before the post to openID

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#49]

**Comment by m273d15** [comment]
The eID data are signed. Therefore we can validate them with the corresponding key.
The key is part of the [PKI (public key infrastructure)](https://www.bsi.bund.de/EN/Topics/ElectrIDDocuments/CSCAcertGermany/cscaGermany_node.html). We have to clarify which key is important and which format is used ( X.509 certificates ).

**Comment by nils-wisiol** [comment]
The eID data will be sent to the eID Server, not to the browser. I think the Django authentication needs to be integrated into the eid token business. Please see the chart referenced in [this post](https://github.com/swp-fu-eid/eid-fu-swp/issues/32#issuecomment-323505074).

**Comment by larissazech** [comment]
Solved by implementing #62.
