### ISSUE TITLE
Add python test execution to travis

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#58]
During the development of eID-types we started to use python tests. Therefore we should run them in the travis pipeline!

**Comment by Armagetron** [comment]
I am on it. Will create a PR when ready

**Comment by Armagetron** [comment]
The CI is up and running in types_ci. I can create a PR after a rebase of add_eid_server_types to master, because I already did this in the test branch or we replay this commit.

**Comment by Armagetron** [comment]
Implemented in 073e6ffc2b7f3b03785bfda0a75118a2ca389bce
