### ISSUE TITLE
Fix the 'modified' gif issue

### ISSUE THREAD

**Issue by nils-wisiol** [swp-fu-eid/eid-fu-swp#59]
by adding `*.gif binary` to `.gitattributes`

**Comment by larissazech** [comment]
Updating my git version to 2.14 solved the issue. As #38 requires to use a git version newer than 2.10, I propose to close this issue and delete the corresponding branch?

**Comment by Armagetron** [comment]
Well it wouldn't hurt to have this extra line. I can create a quick PR if desired

**Comment by larissazech** [comment]
See PR #63. Closed.
