### ISSUE TITLE
Research on OAuth & OpenID Connect

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#8]
Research on OAuth and alternatives

**Comment by Armagetron** [comment]
This [page](https://aaronparecki.com/oauth-2-simplified/) contains a good introduction.

**Comment by baris1892** [comment]
Django OIDC Provider: http://django-oidc-provider.readthedocs.io/en/v0.5.x/sections/installation.html

Die Library könnte eventuell hilfreich sein (vor allem werden sämtliche Python-/Django-Versionen unterstützt!)

**Comment by janles** [comment]
Like @Armagetron mentioned in Slack please read the following very good paper about OpenID Connect: [Heise: OpenID Connect: Login mit OAuth, Teil 1 – Grundlagen](https://www.heise.de/developer/artikel/OpenID-Connect-Login-mit-OAuth-Teil-1-Grundlagen-2218446.html?seite=2).
Independently of @baris1892 I found the same library in my research and this could be very useful for us.
You can find other Django OICD Packages here: [Django Packages - OpenID Connect](https://djangopackages.org/grids/g/oidc/)

**Comment by larissazech** [comment]
I am going to write a summary of the OpenID Connect Specifications that can be obtained here: http://openid.net/developers/specs/. I consider this summary to be the requirement for closing this issue.

**Comment by m273d15** [comment]
Since we are using OpenID it is not necessary to add a OAuth documentation.
